'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MPGP.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  .
        '''</summary>
        Friend ReadOnly Property CipherboxMainform_btnDecipher_Click___() As String
            Get
                Return ResourceManager.GetString("CipherboxMainform_btnDecipher_Click___", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you wish to decipher a hidden file?.
        '''</summary>
        Friend ReadOnly Property CipherboxMainform_btnDecipher_Click_Do_you_wish_to_decipher_a_hidden_file_() As String
            Get
                Return ResourceManager.GetString("CipherboxMainform_btnDecipher_Click_Do_you_wish_to_decipher_a_hidden_file_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error, no password entered. Press OK to exit..
        '''</summary>
        Friend ReadOnly Property CipherboxMainform_btnDecipher_Click_Error__no_password_entered__Press_OK_to_exit_() As String
            Get
                Return ResourceManager.GetString("CipherboxMainform_btnDecipher_Click_Error__no_password_entered__Press_OK_to_exit_"& _ 
                        "", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text Files (*.txt)|*.txt|All Files (*.*)|*.*.
        '''</summary>
        Friend ReadOnly Property CipherboxMainform_btnDecipher_Click_Text_Files____txt____txt_All_Files__________() As String
            Get
                Return ResourceManager.GetString("CipherboxMainform_btnDecipher_Click_Text_Files____txt____txt_All_Files__________", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The data could not be decrypted with the password..
        '''</summary>
        Friend ReadOnly Property CipherboxMainform_btnDecipher_Click_The_data_could_not_be_decrypted_with_the_password_() As String
            Get
                Return ResourceManager.GetString("CipherboxMainform_btnDecipher_Click_The_data_could_not_be_decrypted_with_the_pass"& _ 
                        "word_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  .
        '''</summary>
        Friend ReadOnly Property CipherboxMainform_btnEncipher_Click___() As String
            Get
                Return ResourceManager.GetString("CipherboxMainform_btnEncipher_Click___", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GetFullPath(&apos;{0}&apos;) returns &apos;{1}&apos;.
        '''</summary>
        Friend ReadOnly Property CipherboxMainform_btnEncipher_Click_GetFullPath___0____returns___1__() As String
            Get
                Return ResourceManager.GetString("CipherboxMainform_btnEncipher_Click_GetFullPath___0____returns___1__", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide encrypted file?.
        '''</summary>
        Friend ReadOnly Property CipherboxMainform_btnEncipher_Click_Hide_encrypted_file_() As String
            Get
                Return ResourceManager.GetString("CipherboxMainform_btnEncipher_Click_Hide_encrypted_file_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No password entered. Press OK to exit..
        '''</summary>
        Friend ReadOnly Property CipherboxMainform_btnEncipher_Click_No_password_entered__Press_OK_to_exit_() As String
            Get
                Return ResourceManager.GetString("CipherboxMainform_btnEncipher_Click_No_password_entered__Press_OK_to_exit_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TXT Files (*.txt*)|*.txt.
        '''</summary>
        Friend ReadOnly Property CipherboxMainform_btnEncipher_Click_TXT_Files____txt_____txt() As String
            Get
                Return ResourceManager.GetString("CipherboxMainform_btnEncipher_Click_TXT_Files____txt_____txt", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
